fix: closes all connections when stopped
hapijs/reptile pull request #41
Opened 2018-11-11 09:20 UTC by jaulz

This fix closes all connections when the Hapi server is stopped. Otherwise the node process will continue running until the last connection was closed.

2018-11-11 10:49 UTC, Nargonath requested changes
The travis ci build failed. Please check travis log there are some code format issues (missing semi-colons and so on) plus you'll need to add some tests to cover the new code you added. The coverage was at 100% on last build and usually there is a 100% coverage on all module in HapiJS org.

2018-11-11 12:12 UTC, jaulz commented
Yep, will tackle this tomorrow. Just wanted to get a feeling first if any PR is welcome since the latest welcome is quite old 😊

2018-11-11 12:18 UTC, Nargonath commented
Thanks for your contribution. PR are always welcomed 😉. However I'm not the lead maintainer on this project. I intervened because there were some more work required to make the PR mergeable but in the end @geek will have the final word when it comes to accept or not the contribution.

2018-11-12 13:33 UTC, jaulz commented
@Nargonath @geek I created tests for the new feature but in Node.js v11 some strange things happen with the experimental microtask queue. any idea how we could fix this or if we can ignore this in the meantime?

2018-11-12 14:15 UTC, Nargonath commented
I think there is a problem with Node 11 at the moment. Perhaps @geek just need to disable the Node 11 job for now as it's been done in https://github.com/hapijs/nes/issues/257.

2018-11-12 14:21 UTC, Nargonath approved these changes
I approve the PR based on my previous review because code is now 100% coverage and lint errors have been fixed however someone with more knowledge of the project should have a look at the feature itself.

2018-11-12 14:31 UTC, jaulz commented
Great, thanks! Looking forward for @geek feedback 😊

2018-11-12 17:52 UTC, geek approved these changes

2018-11-12 17:53 UTC, geek commented
@jaulz I'll update master to use different node versions on travis. Thanks for the fix.

2018-11-12 17:53 UTC, merged